apiVersion: apps/v1
kind: Deployment
metadata:
  name: candy-store-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: candy-store
  template:
    metadata:
      labels:
        app: candy-store
    spec:
      containers:
        - name: candy-store
          image: yash5090/candy-store:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
